<?php

require_once __DIR__ . '/Resource.php';

$router->group(['middleware' => ['auth:api', 'verified', 'screenLockDisabled', 'modular:mpis'], 'prefix' => '/api/'.config('app.version').'/mpis'], function() use($router) {
    resource('/personnels', 'MpisService\Transactions\PersonnelController', $router);
    resource('/barangay', 'MpisService\References\BarangayController', $router);
    resource('/bda-size', 'MpisService\References\BdaSizeController', $router);
    resource('/built', 'MpisService\References\BuiltController', $router);
    resource('/citizenship', 'MpisService\References\CitizenshipController', $router);
    resource('/municity', 'MpisService\References\MuniCityController', $router);
    resource('/course', 'MpisService\References\CourseController', $router);
    resource('/education-level', 'MpisService\References\EducationLevelController', $router);
    resource('/ethnic', 'MpisService\References\EthnicController', $router);
    resource('/eye-color', 'MpisService\References\EyeColorController', $router);
    resource('/hair-color', 'MpisService\References\HairColorController', $router);
    resource('/hair-type', 'MpisService\References\HairTypeController', $router);
    resource('/region', 'MpisService\References\RegionController', $router);
    resource('/province', 'MpisService\References\ProvinceController', $router);
    resource('/religion', 'MpisService\References\ReligionController', $router);
    resource('/school', 'MpisService\References\SchoolController', $router);
    resource('/personnel-type', 'MpisService\References\PersonnelTypeController', $router);
    resource('/branch-of-service', 'MpisService\References\BranchOfServiceController', $router);
    resource('/rank', 'MpisService\References\RankController', $router);
    resource('/rank-status', 'MpisService\References\RankStatusController', $router);
    resource('/rank-category', 'MpisService\References\RankCategoryController', $router);
    resource('/personnel-group', 'MpisService\References\PersonnelGroupController', $router);
    resource('/civil-status', 'MpisService\References\CivilStatusController', $router);
    resource('/country', 'MpisService\References\CountryController', $router);
    resource('/training', 'MpisService\References\TrainingController', $router);
    resource('/zipcode', 'OrderPubService\References\ZipcodeOfficeController', $router);

    $router->post('store-personnel-promotion', 'ApiService\v1\MpisService\Transactions\PersonnelController@createPersonnelPromotion');
    $router->get('search-personnel-rank', 'ApiService\v1\MpisService\References\RankController@searchPersonnelRank');
    $router->get('show-zipcode/{id}', 'ApiService\v1\MpisService\Transactions\WorkHistoryController@getZipcodeById');
    $router->get('ethnic-code-search', 'ApiService\v1\MpisService\References\EthnicController@searchEthnic');
    $router->get('personnel-group-search', 'ApiService\v1\MpisService\References\PersonnelGroupController@searchPersonnelGroup');
    $router->get('civil-status-search', 'ApiService\v1\MpisService\References\CitizenshipController@searchCivilStatus');
    $router->get('citizenship-search', 'ApiService\v1\MpisService\References\CitizenshipController@searchCitizenship');
    $router->get('course-type', 'ApiService\v1\MpisService\References\CourseController@getCourseByType');
    $router->post('create-serial', 'ApiService\v1\MpisService\Transactions\SerialNumberController@createSerialNumber');
    $router->post('store-work', 'ApiService\v1\MpisService\Transactions\WorkHistoryController@createWorkHistory');
    $router->get('show-work/{id}', 'ApiService\v1\MpisService\Transactions\WorkHistoryController@getWorkHistory');
    $router->post('store-social-org', 'ApiService\v1\MpisService\Transactions\SocialOrganizationController@createSocialOrg');
    $router->get('show-social-org/{id}', 'ApiService\v1\MpisService\Transactions\SocialOrganizationController@getSocialOrg');
    $router->post('store-insurance', 'ApiService\v1\MpisService\Transactions\InsuranceController@createInsurance');
    $router->get('show-insurance/{id}', 'ApiService\v1\MpisService\Transactions\InsuranceController@getInsurance');
    $router->post('store-government', 'ApiService\v1\MpisService\Transactions\GovernmentIdController@createGovernmentId');
    $router->get('show-government/{id}', 'ApiService\v1\MpisService\Transactions\GovernmentIdController@getGovernmentId');
    $router->post('store-financial', 'ApiService\v1\MpisService\Transactions\FinancialReferenceController@createFinancialReference');
    $router->get('show-financial/{id}', 'ApiService\v1\MpisService\Transactions\FinancialReferenceController@getFinancialReference');
    $router->post('store-eligibility', 'ApiService\v1\MpisService\Transactions\EligibilityController@createElibility');
    $router->get('show-eligibility/{id}', 'ApiService\v1\MpisService\Transactions\EligibilityController@getEligibility');
    $router->post('store-country', 'ApiService\v1\MpisService\Transactions\CountryVisitedController@createCountryVisited');
    $router->get('show-country-visited/{id}', 'ApiService\v1\MpisService\Transactions\CountryVisitedSkillController@getCountryVisited');
    $router->post('store-communication', 'ApiService\v1\MpisService\Transactions\CommunicationSkillController@createCommunicationSkill');
    $router->get('show-communication/{id}', 'ApiService\v1\MpisService\Transactions\CommunicationSkillController@getCommunicationSkill');
    $router->post('store-civilian-commendation', 'ApiService\v1\MpisService\Transactions\CivilianCommendationController@createCommendation');
    $router->get('show-civilian-commendation/{id}', 'ApiService\v1\MpisService\Transactions\CivilianCommendationController@getCommendation');
    $router->post('store-reference', 'ApiService\v1\MpisService\Transactions\CharacterReferenceController@createReference');
    $router->get('show-reference/{id}', 'ApiService\v1\MpisService\Transactions\CharacterReferenceController@getReference');
    $router->get('show-tariff-size/{id}', 'ApiService\v1\MpisService\Transactions\TarrifSizeController@getTarrifSizeById');
    $router->post('store-tariff-size', 'ApiService\v1\MpisService\Transactions\TarrifSizeController@createTarrifSize');
    $router->get('show-characteristic/{id}', 'ApiService\v1\MpisService\Transactions\PersonalCharacteristicController@getPersonalCharacteristicById');
    $router->post('store-characteristic', 'ApiService\v1\MpisService\Transactions\PersonalCharacteristicController@createPersonalCharacteristic');
    $router->get('show-family/{id}', 'ApiService\v1\MpisService\Transactions\FamilyHistoryController@showFamilyHistoryById');
    $router->post('store-family', 'ApiService\v1\MpisService\Transactions\FamilyHistoryController@createFamilyHistory');
    $router->put('update-family/{id}', 'ApiService\v1\MpisService\Transactions\FamilyHistoryController@updateFamilyHistory');
    $router->delete('delete-family/{id}', 'ApiService\v1\MpisService\Transactions\FamilyHistoryController@deleteFamily');
    $router->get('show-education/{id}', 'ApiService\v1\MpisService\References\EducationalBackgroundController@getPersonnelEducationBackground');
    $router->post('store-education', 'ApiService\v1\MpisService\References\EducationalBackgroundController@createPersonnelEducationBackground');
    $router->put('update-education/{id}', 'ApiService\v1\MpisService\References\EducationalBackgroundController@updatePersonnelEducationBackground');
    $router->get('get-province', 'ApiService\v1\MpisService\References\ProvinceController@getProvince');
    $router->get('get-municity', 'ApiService\v1\MpisService\References\MuniCityController@getMunicity');
    $router->get('get-barangay', 'ApiService\v1\MpisService\References\BarangayController@getBarangay');
    $router->get('show-municity/{id}', 'ApiService\v1\MpisService\References\MuniCityController@getMunicityById');
    $router->get('show-province/{id}', 'ApiService\v1\MpisService\References\ProvinceController@getProvinceById');
    $router->get('show-barangay/{id}', 'ApiService\v1\MpisService\References\BarangayController@getBarangayById');
    $router->post('create-personnel-rank', 'ApiService\v1\MpisService\Transactions\PersonnelController@createPersonnelRank');
    $router->post('create-personnel-unit', 'ApiService\v1\MpisService\Transactions\PersonnelController@createPersonnelUnit');
    $router->post('store-address', 'ApiService\v1\MpisService\Transactions\PersonnelController@createPersonnelAddress');
    $router->get('show-address/{id}', 'ApiService\v1\MpisService\Transactions\PersonnelController@getPersonnelAddress');
    $router->put('update-address/{id}', 'ApiService\v1\MpisService\Transactions\PersonnelController@updatePersonnelAddress');
    $router->post('personnel-search', 'ApiService\v1\MpisService\Transactions\PersonnelController@searchPersonnel');
    $router->get('show-personnel/{id}', 'ApiService\v1\MpisService\Transactions\PersonnelController@getPersonnelById');
    $router->get('personnel-total', 'ApiService\v1\MpisService\Transactions\PersonnelController@countPersonnel');
    $router->post('search-info', 'ApiService\v1\MpisService\Transactions\PersonnelController@advanceSearchPersonnel');
    $router->get('show-pmcode/{id}', 'ApiService\v1\MpisService\Transactions\PersonnelController@getPersonnelByPmcode');
    $router->post('upload-image', 'ApiService\v1\MpisService\Transactions\PersonnelController@uploadPersonnelImage');
    $router->post('search-serial-birth', 'ApiService\v1\MpisService\Transactions\PersonnelController@searchPersonnelBySerialNumberBirthdate');
    $router->post('search-serial', 'ApiService\v1\MpisService\Transactions\PersonnelController@searchPersonnelBySerial');
    $router->post('create-personnel', 'ApiService\v1\MpisService\Transactions\PersonnelController@createPersonnel');
    $router->put('update-personnel/{id}', 'ApiService\v1\MpisService\Transactions\PersonnelController@updatePersonnel');
    $router->get('show-rank/{id}', 'ApiService\v1\MpisService\References\RankController@getRankById');
    $router->get('show-training/{id}', 'ApiService\v1\MpisService\References\TrainingController@geTrainingById');
    $router->get('show-personnel-type/{id}', 'ApiService\v1\MpisService\References\PersonnelTypeController@getPersonnelTypeById');

});